[workspace]
members = [
	"cas-attrs",
	"cas-compiler",
	"cas-compute",
	"cas-error",
	"cas-graph",
	"cas-math",
	"cas-parser",
	"cas-repl",
	"cas-vm",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
