[workspace]
members = [
	"cas-attrs",
	"cas-compute",
	"cas-error",
	"cas-graph",
	"cas-math",
	"cas-parser",
	"cas-repl",
	"convert-unit-repl",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
