[package]
name = "cas-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cas-compute = { path = "../cas-compute" }
cas-parser = { path = "../cas-parser" }
